"""changed relationships

Revision ID: 472f903b3e72
Revises: 3173dc7a8c07
Create Date: 2023-05-16 14:21:23.302427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472f903b3e72'
down_revision = '3173dc7a8c07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
