"""changed time column to string in escapes

Revision ID: a429115cb96a
Revises: a27a5d060856
Create Date: 2023-05-18 22:03:55.352141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a429115cb96a'
down_revision = 'a27a5d060856'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
